subscribed_events = [
    { identifier = "deposit", addresses = ["0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2", "0xB8c77482e45F1F44dE1745F52C74426C631bDD52"] }
]

[client_config]
    url = "wss://rpc.sepolia.org"
